apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-academico
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ms-academico
  template:
    metadata:
      labels:
        app: ms-academico
    spec:
      containers:
      - name: ms-academico
        image: unitech/ms-academico:latest
        ports:
        - containerPort: 8082
        env:
        - name: SPRING_DATASOURCE_URL
          value: jdbc:postgresql://postgres-service:5432/academico_db
---
apiVersion: v1
kind: Service
metadata:
  name: ms-academico-service
spec:
  selector:
    app: ms-academico
  ports:
    - protocol: TCP
      port: 8082
      targetPort: 8082
