name: Java CI/CD with Maven and Docker

on:
  push:
    branches: [ "main", "branch-28-implementacao-final" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout do Código
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven

    - name: Build and Test (All Modules)
      run: mvn -B package --file microservicos/pom.xml

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker Image ms-academico
      run: |
        docker build -t unitech/ms-academico:${{ github.sha }} -f ./Dockerfile-template .
      # No mundo real teriamos os pushes pro Docker Hub.
